export const THEMES = [
    {
        title: 'Deep Purple',
        deletable: false,
        colors: {
            layout:"#2f315a",
            main:"#4b4e7c",
            disabled:"#acb1f1",
            primary:"#ea62c3",
            secondary:"#794bec",
            text:"#eaeef9",
        },
    },
    {
        title: 'Blue Bubble Galaxy',
        deletable: false,
        colors: {
            layout:"#727586",
            main:"#505569",
            disabled:"#b9faff",
            primary:"#6fecfe",
            secondary:"#4799fd",
            text:"#8fa4b9",
        },
    },
    {
        title: 'Eco Theme',
        deletable: false,
        colors: {
            layout:"#e6e6e6",
            main:"#fcfcfc",
            disabled:"#d5f15e",
            primary:"#86c481",
            secondary:"#42b49b",
            text:"#319c66",
        },
    },
    {
        title: 'Coral',
        deletable: false,
        colors: {
            layout:"#e1e1e1",
            main:"#ececec",
            disabled:"#acacac",
            primary:"#f75958",
            secondary:"#fb7f81",
            text:"#9c9c9c",
        },
    },
    {
        title: 'Sunny',
        deletable: false,
        colors: {
            layout:"#f8f4eb",
            main:"#fefefe",
            disabled:"#b5b4b2",
            primary:"#ffc85b",
            secondary:"#fd7e51",
            text:"#3c3c3c",
        },
    },
    {
        title: 'Mild Purple',
        deletable: false,
        colors: {
            layout:"#ebe7ff",
            main:"#ffffff",
            disabled:"#c8c7ca",
            primary:"#cbbeff",
            secondary:"#af9fff",
            text:"#8a8690",
        },
    },
    {
        title: 'Pinky',
        deletable: false,
        colors: {
            layout:"#fed9d0",
            main:"#fce7e2",
            disabled:"#C8C8CE",
            primary:"#f6a673",
            secondary:"#d162c9",
            text:"#0F0E0E",
        },
    },
]